# Generated by Django 3.2.8 on 2022-10-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('entry_date', models.DateField()),
                ('out_date', models.DateField()),
                ('roomNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField()),
                ('dispo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sugestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roomNumber', models.IntegerField()),
                ('info', models.CharField(max_length=500)),
                ('doneResponse', models.BooleanField()),
                ('response', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
