# Generated by Django 3.2.8 on 2022-11-03 06:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('roomNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('dispo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('password', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=20)),
                ('username', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('entry_date', models.DateField()),
                ('out_date', models.DateField()),
                ('roomNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='QSugerencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500)),
                ('doneResponse', models.BooleanField(default=False)),
                ('response', models.CharField(default='', max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reservacion')),
                ('roomNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.habitacion')),
            ],
        ),
    ]
