# Generated by Django 3.2.8 on 2022-10-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField()),
                ('dispo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QSugerencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500)),
                ('doneResponse', models.BooleanField()),
                ('response', models.CharField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reservacion')),
                ('roomNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.habitacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Sugestions',
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='roomNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.habitacion'),
        ),
    ]
