# Generated by Django 3.2.8 on 2022-11-04 05:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221104_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='category',
            field=models.CharField(max_length=20, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=15, verbose_name=django.contrib.auth.models.User),
        ),
    ]
